/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomOrder {
  'id' : string,
  'name' : string,
  'description' : string,
  'email' : [] | [string],
  'modelFile' : [] | [ExternalBlob],
  'phone' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type OrderType = { 'custom' : null } |
  { 'store' : null };
export interface PaymentConfirmation {
  'id' : string,
  'customerName' : string,
  'proofFile' : ExternalBlob,
  'orderId' : string,
  'timestamp' : bigint,
}
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface StoreOrder {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'productId' : string,
  'productName' : string,
  'email' : string,
  'paymentProof' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'phone' : string,
  'productPrice' : bigint,
  'productDescription' : string,
}
export interface UnifiedOrder {
  'id' : string,
  'customerName' : string,
  'status' : [] | [string],
  'description' : string,
  'productId' : [] | [string],
  'productName' : [] | [string],
  'orderType' : OrderType,
  'email' : [] | [string],
  'paymentProof' : [] | [ExternalBlob],
  'modelFile' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'phone' : [] | [string],
  'productPrice' : [] | [bigint],
  'productDescription' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'isAdmin' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, ExternalBlob],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllCustomOrders' : ActorMethod<[], Array<CustomOrder>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllPaymentConfirmations' : ActorMethod<[], Array<PaymentConfirmation>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllStoreOrders' : ActorMethod<[], Array<StoreOrder>>,
  'getAllUnifiedOrders' : ActorMethod<[], Array<UnifiedOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryItem' : ActorMethod<[string], GalleryItem>,
  'getPrincipalByEmail' : ActorMethod<[string], [] | [Principal]>,
  'getProduct' : ActorMethod<[string], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUserProfile' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCustomOrder' : ActorMethod<
    [string, string, [] | [string], [] | [string], string, [] | [ExternalBlob]],
    undefined
  >,
  'submitPaymentConfirmation' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'submitStoreOrder' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, ExternalBlob],
    undefined
  >,
  'updateStoreOrderStatus' : ActorMethod<[string, string], undefined>,
  'verifyAndEnsureAdminStatus' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];